main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: lockieluke3389
description: Enable snowball damage
commands:
  winter:
   description: Cooper SMP Winter main command
permissions:
  winter.snowball.damage:
    description: Enable snowball damage
    default: true
  winter.reload:
    description: Reloads the plugin
    default: op
  winter.removeMainHandItem:
    description: Removes the item in your main hand
    default: op
  winter.*:
    description: Grants all winter permissions
    default: false
    children:
      winter.snowball.damage: true
      winter.reload: true
      winter.removeMainHandItem: true

depend: [ ProtocolLib ]