main: ${PACKAGE}.${NAME}
name: ${NAME}
version: "${VERSION}"
api-version: "1.16"
author: lockieluke3389
description: Enable snowball damage
permissions:
  winter.snowball.damage:
    description: Enable snowball damage
    default: true
  winter.reload:
    description: Reloads the plugin
    default: op
  winter.removeMainHandItem:
    description: Removes the item in your main hand
    default: op
  winter.give:
    description: Gives the player a custom item
    default: op
  winter.mockGameMessage:
    description: Mocks a game message
    default: op
  winter.title:
    description: Sends a title to players
    default: op
  winter.downloadAudio:
    description: Downloads audio files
    default: op
  winter.nametag.hide:
    description: Hides the nametag of a player
    default: op
  winter.nametag.show:
    description: Shows the nametag of a player
    default: op
  winter.speaker.stopAll:
    description: Stops all speakers
    default: op
  winter.*:
    description: Grants all winter permissions
    default: false
    children:
      winter.snowball.damage: true
      winter.reload: true
      winter.removeMainHandItem: true
      winter.give: true
      winter.mockGameMessage: true
      winter.title: true
      winter.downloadAudio: true
      winter.nametag.*: true
      winter.speaker.*: true

depend:
  - ProtocolLib
  - CommandAPI